# BASE UI
ColorColumn: "@CursorLine"
Conceal: ""
Cursor: "base3 blue"
CursorIM: ""
CursorColumn: "@CursorLine"
CursorLine: ". base4"
Directory: "blue"
DiffAdd: "base0 green"
DiffChange: "base0 blue"
DiffDelete: "base0 red"
DiffText: "base0 red"
ErrorMsg: "red"
VertSplit: "base0"
Folded: "indigo"
FoldColumn: ""
SignColumn: ""
IncSearch: "yellow base5"
LineNr: "base5 base3"
MatchParen: "blue base4"
ModeMsg: ""
MoreMsg: ""
NonText: "base6"
Normal: "fg bg"
PMenu: ". base3"
PMenuSel: ". base4"
PmenuSbar: ". bg-alt"
PmenuThumb: "base6"
Question: "purple"
Search: "base0 yellow"
SpecialKey: "base3"
SpellBad: "red . u"
SpellLocal: "orange"
SpellCap: "@SpellLocal"
SpellRare: "@SpellRare"
StatusLine: "fg bg-alt"
StatusLineNC: "base3"
TabLine: "indigo bg-alt"
TabLineFill: ". bg-alt"
TabLineSel: "fg bg-alt"
Title: "green"
Visual: ". region"
VisualNOS: ". region"
WarningMsg: "yellow"
WildMenu: "base0 blue"
# BASE SYNTAX
Comment: "indigo"
Constant: "red"
String: "green"
Character: "cyan"
Boolean: "orange"
Number: "orange"
Float: "orange"
Identifier: "red"
Function: "blue"
Statement: "purple"
Conditional: "purple"
Repeat: "purple"
Label: "blue"
Operator: "cyan"
Keyword: "purple"
Exception: "purple"
PreProc: "purple"
Include: "purple"
Define: "purple"
Macro: "light-blue"
PreCondit: "purple"
Type: "orange"
StorageClass: "light-blue"
Structure: "yellow"
Typedef: "yellow"
Special: "cyan"
SpecialChar: "cyan"
Tag: ""
Delimiter: ""
SpecialComment: "@Comment"
Debug: ""
Underlined: ""
Ignore: ""
Error: "red"
Todo: "teal"
