gitconfigComment: '' # Comment
gitconfigSection: '' # Keyword
gitconfigVariable: '' # Identifier
gitconfigBoolean: '' # Boolean
gitconfigNumber: '' # Number
gitconfigString: '' # String
gitconfigDelim: '' # Delimiter
gitconfigEscape: '' # Delimiter
gitconfigError: '' # Error
